package com.revature.exception;

public class UserNotFoundException {
  // this will be tied back to the login failure
}
